<LARPyRoot>
    # Label:
    #     text:"LARPy"
    #     size_hint_y: None
    #     size_hint_x: None
    #     height:"20dp"
    #     width:
    AdminPanel:
        size:(300,300)
        Image:
            # pos: self.pos
            # size: self.size
            source:'resources\graphics\LARPyAdminBG.png'
        # Button:
        #     size_hint_y:None
        #     height: "15dp"
        #     text: "Wut?"
    